### ISSUE TITLE
Configuration screen is not loaded

### ISSUE THREAD

**Issue by arsenaid** [hybridgroup/cylon-pebble#21]
Hi,
I have followed the instructions to install the Watchbot for Pebble IOS. However, when clicked on the settings, the Pebble app keeps spinning forever without showing the settings screen. Any ideas what might be the problem?

P.S. Pebble App: v2.6.5, Watch: v2.9.1

**Comment by deadprogram** [comment]
Hi, @arsenaid we are working on a new Watchbot release that should correct your problem, thanks for reporting.

**Comment by edgarsilva** [comment]
Anyone knows if this has been fixed in latest releases of watchbot?

**Comment by deadprogram** [comment]
Yes, this was addressed in the last release. Can someone with an iOS device please verify?

**Comment by stewart** [comment]
Can confirm it's working now, closing this issue - @arsenaid if you update the app and it's still a problem, please re-open this issue.
